.TH .brunt-dotfiles 1 "May 2024" "Unversioned" "Dotfiles"

.SH DESCRIPTION
.B ~/.brunt-dotfiles/bin

.SH COMMANDS
.TP
.B git-back
Create an instant backup of the working directory of a git repository on a new branch without modifying the working directory, then switch back to the current branch. 

.TP
.B git-find
Search through commits by the text content of their commit message. 

.TP
.B git-forget
"Forget" all files that fit git ignore criteria but have been checked into the repository.

.TP
.B git-ignoretemplate
Append the content of a .gitignore template into the .gitignore file in the current directory. 

.TP 
.B split-video
Split a video file into multiple parts up to a fixed size.

.TP 
.B unix 
Convert a DOS-like path to a UNIX-like path. 

.SH AUTHOR
Written by John Doe.

.SH COPYRIGHT
Copyright \(co 2024 John Doe.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
