# https://docs.atuin.sh/configuration/config/

# database configuration
db_path = "~/.history.db"
key_path = "~/.key"
network_connect_timeout = 5
network_timeout = 5
local_timeout = 5

# localisation
dialect = "uk"
timezone = "local"

# synchronisation & updates
auto_sync = false 
update_check = false 

# search configuration
search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "global"
search_mode_shell_up_key_binding = "fuzzy"

# UI configuration
style = "full"
inline_height = 0
invert = false
show_preview = false 
max_preview_height = 4
history_format = "{time}\t{command}\t{duration}"
show_help = false 
keymap_cursor = { emacs = "blink-block", vim_insert = "blink-block", vim_normal = "steady-block" }
prefers_reduced_motion = true 

# behaviour configuration
exit_mode = "return-original"
word_jump_mode = "emacs"
word_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
scroll_context_lines = 1
ctrl_n_shortcuts = false
enter_accept = true
keymap_mode = "emacs"

# filtering
# don't log commands matching these regexes
history_filter = [
    "^secret-cmd",
    "^innocuous-cmd .*--secret=.+"
]
# don't log commands in directories matching these regexes
cwd_filter = [
    "^/very/secret/area"
]
# apply a standard set (AWS key ID, GitHub PAT, Slack OAuth tokens & webhooks, Stripe keys
secrets_filter = true

[stats]
common_subcommands = [
    "cargo",
    "git",
    "npm"
]
# strip common prefixes
common_prefix = ["sudo"]