set-option -g prefix ^b # <C-b> default

# Keybind to quickly reload config
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Enable mouse movements
set -g mouse on

# Alt-arrow to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Horizontal and vertical window split
bind-key v split-window -h
bind-key h split-window -v

# <C-S-arrow> to reorder windows
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Theming
set -g status-justify centre
set-option -g status-style bg=default
set -g status-fg colour35
set -g status-interval 60
set -g status-left-length 50
set -g status-left "#[bg=#dbd3f7]💻#[fg=#000000,bold] #H#[bg=#dbd3f7]#[bg=#dbd3f7,nobold]#[fg=colour234] [#S] $tmux_target_lower"
set -g status-right '#[bg=#dbd3f7] 🕔 #[fg=colour234,bold]%H:%M '

# tpm
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'frappe'

run '~/.tmux/plugins/tpm/tpm' # keep at bottom of conf file