alias ls="exa"
alias cat="batcat"
alias ffmpreg="ffmpeg"
alias top="bashtop"
alias ripgrep="rg"

alias rtfm="tail -n 1 $HOME/.bash_history | awk '{print $1}' | xargs man"

bind '"\C-o": "\C-usource $HOME/.brunt-dotfiles/scripts/open_work_project.sh\n"'
bind -x '"\C-r": source $HOME/.bashrc'